title: Aprendiendo jekyll desde github
author: Santiago Lombardi
email: santilomb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Un ejercicio practico para ir entendiendo el renderizado de jekyll
theme: minima

# social links
twitter_username: santilomb # DO NOT include the @ character, or else the build will fail!
github_username:  santilomb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
